```{r}
data = read.csv('../data/train.csv')
```

```{r}
# plot correlation matrix of some selected features
library(ggcorrplot)

selected_data = data[, c('Elevation', 'Aspect', 'Slope', 'Horizontal_Distance_To_Hydrology', 
                         'Vertical_Distance_To_Hydrology', 'Horizontal_Distance_To_Roadways', 
                         'Hillshade_9am', 'Hillshade_Noon', 'Horizontal_Distance_To_Fire_Points')
                     ]

correlation_matrix <- round(cor(selected_data), 3)
ggcorrplot(correlation_matrix)

```

```{r}

# scatter plots

x <- data$Elevation
y <- data$Aspect

plot(x, y, xlab='Elevation', ylab='Aspect', main='Scatter plot of Elevation and Aspect')
abline(lm(y ~ x, data = data), col = "blue")

x <- data$Horizontal_Distance_To_Hydrology
y <- data$Vertical_Distance_To_Hydrology

plot(x, y, xlab='Horizontal_Distance_To_Hydrology', ylab='Vertical_Distance_To_Hydrology', main='Scatter plot of Horizontal_Distance_To_Hydrology and Vertical_Distance_To_Hydrology')
abline(lm(y ~ x, data = data), col = "blue")

x <- data$Elevation
y <- data$Slope
plot(x, y, xlab='Elevation', ylab='Slope', main='Scatter plot of Elevation and Slope')
abline(lm(y ~ x, data = data), col = "blue")

x <- data$Aspect
y <- data$Slope
plot(x, y, xlab='Aspect', ylab='Slope', main='Scatter plot of Aspect and Slope')
abline(lm(y ~ x, data = data), col = "blue")

x <- data$Cover_Type
y <- data$Horizontal_Distance_To_Roadways
plot(x, y, xlab='Cover_Type', ylab='Horizontal_Distance_To_Roadways', main='Scatter plot of CoverType and Horizontal_Distance_To_Roadways')

x <- data$Cover_Type
y <- data$Horizontal_Distance_To_Fire_Points
plot(x, y, xlab='Cover_Type', ylab='Horizontal_Distance_To_Fire_Points', main='Scatter plot of CoverType and Horizontal_Distance_To_Fire_Points')
```

```{r}
# computing PCA
selected_data_pca = data[, c('Elevation', 'Aspect', 'Slope', 'Horizontal_Distance_To_Hydrology', 
                             'Vertical_Distance_To_Hydrology', 'Horizontal_Distance_To_Roadways', 
                             'Hillshade_9am', 'Hillshade_Noon', 'Hillshade_3pm', 'Horizontal_Distance_To_Fire_Points')
                     ]

pca <- prcomp(selected_data_pca, center=TRUE, scale=FALSE)
summary(pca)
pca$rotation

```

```{r}

# see correlation between first 2 principal components and cover type
library(scatterplot3d)

x1 <- t(t(pca$rotation[, 1]) %*% t(selected_data_pca))
x2 <- t(t(pca$rotation[, 2]) %*% t(selected_data_pca))
y <- data$Cover_Type

colors <- c("#FF0000", "#906C6C", "#5E3DFF", "#00EFFF", "#00FF4D", "#9AFF00", "#FFEF00")
scatterplot3d(x=y, y=x1, z=x2, ylab="1 PC", xlab="Cover Type", zlab="2 PC", color=colors[as.numeric(y)])

```

```{r}

library(ggbiplot)
ggbiplot(pca)

```
```{r}
library(pca3d)
gr <- factor(data$Cover_Type)
pca3d(pca, group=gr, biplot=TRUE, biplot.vars=3, legend="topleft", show.ellipses = TRUE)
```

```{r}
data = read.csv('../data/train.csv')
data = data[-1]
library(Rtsne)
data$Cover_Type = as.factor(data$Cover_Type)
colors = rainbow(length(unique(data$Cover_Type)))
names(colors) = unique(data$Cover_Type)
tsne = Rtsne(data, dims = 2, perplexity=45, verbose=TRUE, max_iter = 1000)
plot(tsne$Y, t='n', main='bidimensional mapping')
text(tsne$Y, labels=data$Cover_Type, col=colors[data$Cover_Type])
```

```{r}
library(corrgram)
data = read.csv('../data/train.csv')[-1]
corrgram(data[-11:(-length(data) + 1)], order=T, lower.panel=panel.pts, upper.panel=panel.pie, text.panel=panel.txt, main="Corrgrams")
```

```{r}
library(MASS)

data = read.csv('../data/train.csv')[-1]
data.ppr = ppr(Cover_Type ~ Elevation + Aspect + Slope + Horizontal_Distance_To_Hydrology, data=data, nterms=4)
#par(mfrow = c(1, 10))
plot(data.ppr, main = "ppr(Cover_Type~)")
plot(update(data.ppr, sm.method = "gcv", gcvpen = 2),main = "update gcv")
```
